name       : haskell-x11
version    : 1.9.1
release    : 4
source     :
    - https://hackage.haskell.org/package/X11-1.9.1/X11-1.9.1.tar.gz : 7581e7b3c1c8313d1f7d224d57b20c689e5f757404c9f0ec47f4d15c4541e63d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell binding to the X11 graphics library
description: |
    Haskell binding to the X11 graphics library
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - haskell-cabal-install
    - haskell-data-default-devel
rundeps    :
    - devel:
        - haskell-data-default-devel
        - libxinerama-devel
        - libxrandr-devel
        - libxscrnsaver-devel
networking : yes
optimize   : no-symbolic
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
