name       : haskell-x11
version    : '1.9'
release    : 3
source     :
    - https://hackage.haskell.org/package/X11-1.9/X11-1.9.tar.gz : 10138e863d8c6f860aad1755a6f1a36949cc02d83e5afacf6677fb3999f10db9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell binding to the X11 graphics library
description: |
    Haskell binding to the X11 graphics library
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - haskell-cabal-install
    - haskell-data-default
optimize   : no-symbolic
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
