name       : haskell-x11
version    : 1.8
release    : 1
source     :
    - https://hackage.haskell.org/package/X11-1.8/X11-1.8.tar.gz : 541b166aab1e05a92dc8f42a511d827e7aad373af12ae283b9df9982ccc09d8e
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell binding to the X11 graphics library
description: |
    Haskell binding to the X11 graphics library
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - haskell-cabal-install
    - haskell-data-default
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
