name       : haskell-x11
version    : 1.10.3
release    : 5
source     :
    - https://hackage.haskell.org/package/X11-1.10.3/X11-1.10.3.tar.gz : d84ad1b8f5cdb65a0de17f84d765ebbb7aeeab9608c3740804da28100616d242
license    : BSD-3-Clause
component  : programming.haskell
summary    : Haskell binding to the X11 graphics library
description: |
    Haskell binding to the X11 graphics library
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - haskell-cabal-install
    - haskell-data-default-class-devel
rundeps    :
    - devel :
        - haskell-data-default-class-devel
        - libxinerama-devel
        - libxrandr-devel
        - libxscrnsaver-devel
networking : yes
optimize   : no-symbolic
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
